# Site settings
title: "willmartian.com ðŸ‘½&#xFE0E;"
description: "Space Pirate of the Open Web"
baseurl: "" # required if used under gh-pages branch, else (under master branch) just leave empty/blank
url: ""
author: "William Martin"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname: willmartian

plugins:
  - jekyll-sitemap
  - jekyll-admin